services:
    KTPL\CurrencyRateConversionBundle\Commands\InstallationCommand:
        arguments:
            - '@akeneo_batch.job.job_instance_repository'
        tags:
            - { name: console.command }