services:
    ktpl.currency_rate_conversion.connector.processor.mass_edit.product.edit_attributes:
        class: 'KTPL\CurrencyRateConversionBundle\Connector\Processor\MassEdit\EditAttributesProcessor'
        arguments:
            - '@pim_catalog.validator.product'
            - '@pim_catalog.validator.product_model'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.updater.product_model'
            - '@pim_catalog.repository.cached_attribute'
            - '@pim_catalog.entity_with_family_variant.check_attribute_editable'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_catalog.comparator.filter.product_model'
            - '@pim_catalog.repository.currency'