services:
    ktpl.currency_rate_conversion.step.compute_currency_conversion:
      class: '%pim_connector.step.item_step.class%'
      arguments:
          - 'compute_currency_rate_conversion'
          - '@event_dispatcher'
          - '@akeneo_batch.job_repository'
          - '@ktpl.currency_rate_conversion.reader.database.product_and_product_model'
          - '@ktpl.currency_rate_conversion.connector.processor.mass_edit.product.edit_attributes'
          - '@pim_enrich.writer.database.product_and_product_model_writer'
          - '%pim_job_product_batch_size%'
          - '@akeneo_batch.job.job_stopper'